# Generated by Django 5.0 on 2023-12-16 11:30

import autoslug.fields
import restaurant.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_category_slug_alter_fooditem_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fooditem',
            options={},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=restaurant.models.russian_slugify, unique=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=restaurant.models.russian_slugify, unique=True),
        ),
    ]
