# Generated by Django 5.0 on 2023-12-16 11:34

import autoslug.fields
import django.db.models.deletion
import restaurant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_category_options_alter_fooditem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='fooditem',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='name', slugify=restaurant.models.russian_slugify, unique=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.category'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='name', slugify=restaurant.models.russian_slugify, unique=True),
        ),
    ]
